version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: 1
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: counter_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
